### ISSUE TITLE
Base64 review #1

### ISSUE THREAD

**Issue by avkomar** [S1x6/base64#3]
Вадим, 
см замечания в [открытом pull-request](https://github.com/S1x6/base64/pull/2)

**Comment by S1x6** [comment]
Откорректировал код, разобрался с консолью Git, возник вопрос, что хранить в репозитории, только файлы с кодом или весь проект?
Не добавил комментарии ибо они при загрузке все равно портятся кодировкой (разве что на английском их писать)

P.S. Попробовал закодировать саму программу, получилось, после декодирования отработала как надо

**Comment by avkomar** [comment]
1. Храните в репозитории только код.
2. Для русских комментариев в настройках Visual Studio нужно настроить автоматическое сохранение в Unicode (UTF-8)
Можно посмотреть настройку: 
`Tools > Options > Environment > Documents > Save documents as Unicode when data cannot be saved in codepage` 

3. Из замечаний, для невалидного кода в обратной таблице вместо магического числа `65` нужно использовать именованную константу `INVALID_CODE`

4. в parsing.c  по-прежнему нету проверки на то, что `argv[i + 1]` и `argv[i + 2]` не `NULL` 

Считайте, что задача принята.
